import Head from 'next/head'
import {getSession} from "next-auth/react"
import Header from "../components/Header"
import Login from "../components/Login"
import Sidebar from "../components/Sidebar"
import Feed from "../components/Feed"
import RightSideBar from "../components/RightSideBar"
export default function Home({session}) {
  if(!session) return <Login/>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className='flex bg-gray-100'>
        <Sidebar></Sidebar>
        <Feed/>
        <RightSideBar/>
      </main>
    </>
  )
}

export async function getServerSideProps(context){
  const session=await getSession (context);
  console.log(session)
  return {
    props:{session}
  };
}
